version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db/mysql:/var/lib/mysql
     ports:
       - "3306-3385:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - ./themes/:/var/www/html/wp-content/themes
      - ./wordpress/:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
     ports:
       - "8000-8079:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
